//Đăng kí tài khoản
POST http://localhost:3500/user/register
Content-Type: application/json

{
    "username": "anh1",
    "password": "anh"
}

###
//Đăng nhập tài khoản
POST http://localhost:3500/user/auth
Content-Type: application/json

{
    "username": "anh1",
    "password": "anh"
}

###
//Tạo bài viết, nhớ lấy lại accessToken và dán lại
POST http://localhost:3500/post/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3IiOnsidXNlcm5hbWUiOiJhbmgxIiwidXNlcklEIjoiNjkyNWJmYWM2NzczN2E3Njk4MThmNWI1In0sImlhdCI6MTc2NDI1NjgwOSwiZXhwIjoxNzY0MzQzMjA5fQ.B0CctV4A2z83dlhIJjqVcQD0pUWuYYXBVxjOg3KMUYY
Content-Type: application/json

{
    "content": "Post thứ hai của tôi"
}

###
//Lấy bài viết theo id, nhớ lấy id User và dán lại
GET http://localhost:3500/post/6925bfac67737a769818f5b5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3IiOnsidXNlcm5hbWUiOiJhbmgxIiwidXNlcklEIjoiNjkyNWJmYWM2NzczN2E3Njk4MThmNWI1In0sImlhdCI6MTc2NDI1NTI0MSwiZXhwIjoxNzY0MzQxNjQxfQ.AuDB8ludc7PWqAskgvgd_DjtlLMa7PCpnu6fXzEAQF4

###
//Tạo comment, nhớ lấy id của post và dán lại
POST http://localhost:3500/comment/6925bfac67737a769818f5b5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3IiOnsidXNlcm5hbWUiOiJhbmgxIiwidXNlcklEIjoiNjkyNWJmYWM2NzczN2E3Njk4MThmNWI1In0sImlhdCI6MTc2NDI1NjYzOSwiZXhwIjoxNzY0MzQzMDM5fQ.4TRrXqZffeIfxTfcHZcli3290n8appjeUDxQhv3o8oM
Content-Type: application/json

{
    "content": "Comment đầu tiên của tôi"
}

###
//Xóa comment, nhớ lấy id của comment và dán lại
DELETE http://localhost:3500/comment/6925bfac67737a769818f5b5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3IiOnsidXNlcm5hbWUiOiJhbmgxIiwidXNlcklEIjoiNjkyNWJmYWM2NzczN2E3Njk4MThmNWI1In0sImlhdCI6MTc2NDI1NjYzOSwiZXhwIjoxNzY0MzQzMDM5fQ.4TRrXqZffeIfxTfcHZcli3290n8appjeUDxQhv3o8oM

###
//Like post, nhớ lấy id của post và gán lại
PUT http://localhost:3500/like/69286cb50d0f22077f8b8c10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3IiOnsidXNlcm5hbWUiOiJhbmgxIiwidXNlcklEIjoiNjkyNWJmYWM2NzczN2E3Njk4MThmNWI1In0sImlhdCI6MTc2NDI1NjYzOSwiZXhwIjoxNzY0MzQzMDM5fQ.4TRrXqZffeIfxTfcHZcli3290n8appjeUDxQhv3o8oM

###
//Lấy số lượng like của post, nhớ lấy id của post và gán lại
GET http://localhost:3500/like/69286cb50d0f22077f8b8c10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3IiOnsidXNlcm5hbWUiOiJhbmgxIiwidXNlcklEIjoiNjkyNWJmYWM2NzczN2E3Njk4MThmNWI1In0sImlhdCI6MTc2NDI1NjYzOSwiZXhwIjoxNzY0MzQzMDM5fQ.4TRrXqZffeIfxTfcHZcli3290n8appjeUDxQhv3o8oM





